# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true

# Kotlin
kotlin.code.style=official

# Android
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.useAndroidX=true

# Override non-ASCII path check (project is in Cyrillic path)
android.overridePathCheck=true

# Kapt settings for stability with Kotlin 2.1
kapt.use.worker.api=false
kapt.incremental.apt=false